"""add_geofence_and_device_binding

Revision ID: 8f1bd6b4c043
Revises: b234f567890c
Create Date: 2026-07-18 10:17:13.507567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f1bd6b4c043'
down_revision: Union[str, Sequence[str], None] = 'b234f567890c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_class_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_student_id'), table_name='attendance')
    op.add_column('classes', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('classes', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('classes', sa.Column('radius_meters', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_face_embeddings_student_id'), table_name='face_embeddings')
    op.add_column('students', sa.Column('device_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'device_id')
    op.create_index(op.f('ix_face_embeddings_student_id'), 'face_embeddings', ['student_id'], unique=False)
    op.drop_column('classes', 'radius_meters')
    op.drop_column('classes', 'longitude')
    op.drop_column('classes', 'latitude')
    op.create_index(op.f('ix_attendance_student_id'), 'attendance', ['student_id'], unique=False)
    op.create_index(op.f('ix_attendance_class_id'), 'attendance', ['class_id'], unique=False)
    # ### end Alembic commands ###
